# Generated by Django 4.0.6 on 2022-08-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_alter_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='i_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
