# Generated by Django 4.0.6 on 2022-08-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_rename_i_name_menu_name_remove_menu_i_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menus',
        ),
    ]
