# Generated by Django 4.0.6 on 2022-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu',
            new_name='product',
        ),
        migrations.AddField(
            model_name='menus',
            name='orderstat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
