# Generated by Django 4.0.6 on 2022-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_rename_menu_order_product_menus_orderstat_order_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='orderstat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='menus',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='orderstat',
            field=models.BooleanField(default=False),
        ),
    ]
