# Generated by Django 4.0.6 on 2022-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_remove_menus_orderstat_remove_order_qty_menus_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
